apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: workshop-spok
  region: us-east-2
  version: "1.22"
managedNodeGroups:
  - name: ng-ondemand
    minSize: 1
    maxSize: 5
    desiredCapacity: 1
    instanceType: t3.medium
    volumeSize: 10
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
#       - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      withAddonPolicies:
        autoscaler: true
  - name: ng-spot
    minSize: 1
    maxSize: 5
    desiredCapacity: 2
    instanceType: t3.medium
    spot: True
    volumeSize: 10
    iam:
      attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      withAddonPolicies:
        autoscaler: true

